window.MATCH_DATA = [
 {
  "n": 1,
  "title": "Mexico vs. South Africa",
  "home": "Mexico",
  "away": "South Africa",
  "homeZh": "墨西哥",
  "awayZh": "南非",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "A",
  "homeOdds": 1.4299,
  "drawOdds": 4.8216,
  "awayOdds": 9.0982,
  "result": "home",
  "score": "2-0",
  "homeRank": 14,
  "awayRank": 60,
  "rankDiff": -46,
  "favorite": "home",
  "kickoff": "2026-06-12 03:00"
 },
 {
  "n": 2,
  "title": "Korea Republic vs. Czechia",
  "home": "Korea Republic",
  "away": "Czechia",
  "homeZh": "韩国",
  "awayZh": "捷克",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "A",
  "homeOdds": 2.6349,
  "drawOdds": 3.125,
  "awayOdds": 3.1276,
  "result": "home",
  "score": "2-1",
  "homeRank": 25,
  "awayRank": 40,
  "rankDiff": -15,
  "favorite": "home",
  "kickoff": "2026-06-12 10:00"
 },
 {
  "n": 3,
  "title": "Canada vs. Bosnia-Herzegovina",
  "home": "Canada",
  "away": "Bosnia-Herzegovina",
  "homeZh": "加拿大",
  "awayZh": "波黑",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "B",
  "homeOdds": 1.852,
  "drawOdds": 3.5715,
  "awayOdds": 5.0,
  "result": "draw",
  "score": "1-1",
  "homeRank": 30,
  "awayRank": 64,
  "rankDiff": -34,
  "favorite": "home",
  "kickoff": "2026-06-13 03:00"
 },
 {
  "n": 4,
  "title": "United States vs. Paraguay",
  "home": "United States",
  "away": "Paraguay",
  "homeZh": "美国",
  "awayZh": "巴拉圭",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "D",
  "homeOdds": 2.1295,
  "drawOdds": 3.3333,
  "awayOdds": 4.2163,
  "result": "home",
  "score": "4-1",
  "homeRank": 17,
  "awayRank": 41,
  "rankDiff": -24,
  "favorite": "home",
  "kickoff": "2026-06-13 09:00"
 },
 {
  "n": 5,
  "title": "Haiti vs. Scotland",
  "home": "Haiti",
  "away": "Scotland",
  "homeZh": "海地",
  "awayZh": "苏格兰",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "C",
  "homeOdds": 6.25,
  "drawOdds": 4.7619,
  "awayOdds": 1.5908,
  "result": "away",
  "score": "0-1",
  "homeRank": 83,
  "awayRank": 42,
  "rankDiff": 41,
  "favorite": "away",
  "kickoff": "2026-06-14 09:00"
 },
 {
  "n": 6,
  "title": "Australia vs. Türkiye",
  "home": "Australia",
  "away": "Türkiye",
  "homeZh": "澳大利亚",
  "awayZh": "土耳其",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "D",
  "homeOdds": 5.5556,
  "drawOdds": 3.8462,
  "awayOdds": 1.7544,
  "result": "home",
  "score": "2-0",
  "homeRank": 27,
  "awayRank": 22,
  "rankDiff": 5,
  "favorite": "away",
  "kickoff": "2026-06-14 12:00"
 },
 {
  "n": 7,
  "title": "Brazil vs. Morocco",
  "home": "Brazil",
  "away": "Morocco",
  "homeZh": "巴西",
  "awayZh": "摩洛哥",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "C",
  "homeOdds": 1.6951,
  "drawOdds": 3.8462,
  "awayOdds": 5.8842,
  "result": "draw",
  "score": "1-1",
  "homeRank": 6,
  "awayRank": 7,
  "rankDiff": -1,
  "favorite": "home",
  "kickoff": "2026-06-14 06:00"
 },
 {
  "n": 8,
  "title": "Qatar vs. Switzerland",
  "home": "Qatar",
  "away": "Switzerland",
  "homeZh": "卡塔尔",
  "awayZh": "瑞士",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "B",
  "homeOdds": 16.6667,
  "drawOdds": 7.6923,
  "awayOdds": 1.2052,
  "result": "draw",
  "score": "1-1",
  "homeRank": 56,
  "awayRank": 19,
  "rankDiff": 37,
  "favorite": "away",
  "kickoff": "2026-06-14 03:00"
 },
 {
  "n": 9,
  "title": "Côte d'Ivoire vs. Ecuador",
  "home": "Côte d'Ivoire",
  "away": "Ecuador",
  "homeZh": "科特迪瓦",
  "awayZh": "厄瓜多尔",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "E",
  "homeOdds": 3.5754,
  "drawOdds": 2.9412,
  "awayOdds": 2.5643,
  "result": "home",
  "score": "1-0",
  "homeRank": 33,
  "awayRank": 23,
  "rankDiff": 10,
  "favorite": "away",
  "kickoff": "2026-06-15 07:00"
 },
 {
  "n": 10,
  "title": "Germany vs. Curaçao",
  "home": "Germany",
  "away": "Curaçao",
  "homeZh": "德国",
  "awayZh": "库拉索",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "E",
  "homeOdds": 1.0566,
  "drawOdds": 27.5936,
  "awayOdds": 41.9995,
  "result": "home",
  "score": "7-1",
  "homeRank": 10,
  "awayRank": 82,
  "rankDiff": -72,
  "favorite": "home",
  "kickoff": "2026-06-15 01:00"
 },
 {
  "n": 11,
  "title": "Netherlands vs. Japan",
  "home": "Netherlands",
  "away": "Japan",
  "homeZh": "荷兰",
  "awayZh": "日本",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "F",
  "homeOdds": 2.1744,
  "drawOdds": 3.4515,
  "awayOdds": 3.7148,
  "result": "draw",
  "score": "2-2",
  "homeRank": 8,
  "awayRank": 18,
  "rankDiff": -10,
  "favorite": "home",
  "kickoff": "2026-06-15 04:00"
 },
 {
  "n": 12,
  "title": "Sweden vs. Tunisia",
  "home": "Sweden",
  "away": "Tunisia",
  "homeZh": "瑞典",
  "awayZh": "突尼斯",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "F",
  "homeOdds": 1.9612,
  "drawOdds": 3.4501,
  "awayOdds": 4.8013,
  "result": "home",
  "score": "5-1",
  "homeRank": 38,
  "awayRank": 45,
  "rankDiff": -7,
  "favorite": "home",
  "kickoff": "2026-06-15 10:00"
 },
 {
  "n": 13,
  "title": "Saudi Arabia vs. Uruguay",
  "home": "Saudi Arabia",
  "away": "Uruguay",
  "homeZh": "沙特阿拉伯",
  "awayZh": "乌拉圭",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "H",
  "homeOdds": 8.3626,
  "drawOdds": 4.548,
  "awayOdds": 1.4706,
  "result": "draw",
  "score": "1-1",
  "homeRank": 61,
  "awayRank": 16,
  "rankDiff": 45,
  "favorite": "away",
  "kickoff": "2026-06-16 06:00"
 },
 {
  "n": 14,
  "title": "Spain vs. Cabo Verde",
  "home": "Spain",
  "away": "Cabo Verde",
  "homeZh": "西班牙",
  "awayZh": "佛得角",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "H",
  "homeOdds": 1.0754,
  "drawOdds": 18.7228,
  "awayOdds": 43.4827,
  "result": "draw",
  "score": "0-0",
  "homeRank": 2,
  "awayRank": 67,
  "rankDiff": -65,
  "favorite": "home",
  "kickoff": "2026-06-16 00:00"
 },
 {
  "n": 15,
  "title": "IR Iran vs. New Zealand",
  "home": "IR Iran",
  "away": "New Zealand",
  "homeZh": "伊朗",
  "awayZh": "新西兰",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "G",
  "homeOdds": 1.8572,
  "drawOdds": 3.5752,
  "awayOdds": 5.0005,
  "result": "draw",
  "score": "2-2",
  "homeRank": 20,
  "awayRank": 85,
  "rankDiff": -65,
  "favorite": "home",
  "kickoff": "2026-06-16 09:00"
 },
 {
  "n": 16,
  "title": "Belgium vs. Egypt",
  "home": "Belgium",
  "away": "Egypt",
  "homeZh": "比利时",
  "awayZh": "埃及",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "G",
  "homeOdds": 1.5629,
  "drawOdds": 4.1689,
  "awayOdds": 6.6708,
  "result": "draw",
  "score": "1-1",
  "homeRank": 9,
  "awayRank": 29,
  "rankDiff": -20,
  "favorite": "home",
  "kickoff": "2026-06-16 03:00"
 },
 {
  "n": 17,
  "title": "France vs. Senegal",
  "home": "France",
  "away": "Senegal",
  "homeZh": "法国",
  "awayZh": "塞内加尔",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "I",
  "homeOdds": 1.4706,
  "drawOdds": 4.5553,
  "awayOdds": 7.7925,
  "result": "home",
  "score": "3-1",
  "homeRank": 3,
  "awayRank": 15,
  "rankDiff": -12,
  "favorite": "home",
  "kickoff": "2026-06-17 03:00"
 },
 {
  "n": 18,
  "title": "Iraq vs. Norway",
  "home": "Iraq",
  "away": "Norway",
  "homeZh": "伊拉克",
  "awayZh": "挪威",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "I",
  "homeOdds": 14.315,
  "drawOdds": 7.1731,
  "awayOdds": 1.2346,
  "result": "away",
  "score": "1-4",
  "homeRank": 57,
  "awayRank": 31,
  "rankDiff": 26,
  "favorite": "away",
  "kickoff": "2026-06-17 06:00"
 },
 {
  "n": 19,
  "title": "Argentina vs. Algeria",
  "home": "Argentina",
  "away": "Algeria",
  "homeZh": "阿根廷",
  "awayZh": "阿尔及利亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "J",
  "homeOdds": 1.5386,
  "drawOdds": 4.3491,
  "awayOdds": 7.7008,
  "result": "home",
  "score": "3-0",
  "homeRank": 1,
  "awayRank": 28,
  "rankDiff": -27,
  "favorite": "home",
  "kickoff": "2026-06-17 09:00"
 },
 {
  "n": 20,
  "title": "Austria vs. Jordan",
  "home": "Austria",
  "away": "Jordan",
  "homeZh": "奥地利",
  "awayZh": "约旦",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "J",
  "homeOdds": 1.4287,
  "drawOdds": 5.1194,
  "awayOdds": 9.0415,
  "result": "home",
  "score": "3-1",
  "homeRank": 24,
  "awayRank": 63,
  "rankDiff": -39,
  "favorite": "home",
  "kickoff": "2026-06-17 12:00"
 },
 {
  "n": 21,
  "title": "Ghana vs. Panama",
  "home": "Ghana",
  "away": "Panama",
  "homeZh": "加纳",
  "awayZh": "巴拿马",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "L",
  "homeOdds": 2.4418,
  "drawOdds": 3.2263,
  "awayOdds": 3.3362,
  "result": "home",
  "score": "1-0",
  "homeRank": 73,
  "awayRank": 34,
  "rankDiff": 39,
  "favorite": "home",
  "kickoff": "2026-06-18 07:00"
 },
 {
  "n": 22,
  "title": "England vs. Croatia",
  "home": "England",
  "away": "Croatia",
  "homeZh": "英格兰",
  "awayZh": "克罗地亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "L",
  "homeOdds": 1.7243,
  "drawOdds": 3.8462,
  "awayOdds": 5.5558,
  "result": "home",
  "score": "4-2",
  "homeRank": 4,
  "awayRank": 11,
  "rankDiff": -7,
  "favorite": "home",
  "kickoff": "2026-06-18 04:00"
 },
 {
  "n": 23,
  "title": "Portugal vs. DR Congo",
  "home": "Portugal",
  "away": "DR Congo",
  "homeZh": "葡萄牙",
  "awayZh": "刚果民主共和国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "K",
  "homeOdds": 1.2988,
  "drawOdds": 5.8828,
  "awayOdds": 12.5,
  "result": "draw",
  "score": "1-1",
  "homeRank": 5,
  "awayRank": 46,
  "rankDiff": -41,
  "favorite": "home",
  "kickoff": "2026-06-18 01:00"
 },
 {
  "n": 24,
  "title": "Uzbekistan vs. Colombia",
  "home": "Uzbekistan",
  "away": "Colombia",
  "homeZh": "乌兹别克斯坦",
  "awayZh": "哥伦比亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 1,
  "group": "K",
  "homeOdds": 10.5034,
  "drawOdds": 5.0,
  "awayOdds": 1.3957,
  "result": "away",
  "score": "1-3",
  "homeRank": 50,
  "awayRank": 13,
  "rankDiff": 37,
  "favorite": "away",
  "kickoff": "2026-06-18 10:00"
 },
 {
  "n": 25,
  "title": "Czechia vs. South Africa",
  "home": "Czechia",
  "away": "South Africa",
  "homeZh": "捷克",
  "awayZh": "南非",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "A",
  "homeOdds": 1.8538,
  "drawOdds": 3.7038,
  "awayOdds": 4.794,
  "result": "draw",
  "score": "1-1",
  "homeRank": 40,
  "awayRank": 60,
  "rankDiff": -20,
  "favorite": "home",
  "kickoff": "2026-06-19 00:00"
 },
 {
  "n": 26,
  "title": "Switzerland vs. Bosnia-Herzegovina",
  "home": "Switzerland",
  "away": "Bosnia-Herzegovina",
  "homeZh": "瑞士",
  "awayZh": "波黑",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "B",
  "homeOdds": 1.588,
  "drawOdds": 4.1736,
  "awayOdds": 6.6705,
  "result": "home",
  "score": "4-1",
  "homeRank": 19,
  "awayRank": 64,
  "rankDiff": -45,
  "favorite": "home",
  "kickoff": "2026-06-19 03:00"
 },
 {
  "n": 27,
  "title": "Canada vs. Qatar",
  "home": "Canada",
  "away": "Qatar",
  "homeZh": "加拿大",
  "awayZh": "卡塔尔",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "B",
  "homeOdds": 1.3166,
  "drawOdds": 5.8827,
  "awayOdds": 11.1111,
  "result": "home",
  "score": "6-0",
  "homeRank": 30,
  "awayRank": 56,
  "rankDiff": -26,
  "favorite": "home",
  "kickoff": "2026-06-19 06:00"
 },
 {
  "n": 28,
  "title": "Mexico vs. Korea Republic",
  "home": "Mexico",
  "away": "Korea Republic",
  "homeZh": "墨西哥",
  "awayZh": "韩国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "A",
  "homeOdds": 2.0835,
  "drawOdds": 3.3334,
  "awayOdds": 4.1669,
  "result": "home",
  "score": "1-0",
  "homeRank": 14,
  "awayRank": 25,
  "rankDiff": -11,
  "favorite": "home",
  "kickoff": "2026-06-19 09:00"
 },
 {
  "n": 29,
  "title": "Brazil vs. Haiti",
  "home": "Brazil",
  "away": "Haiti",
  "homeZh": "巴西",
  "awayZh": "海地",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "C",
  "homeOdds": 1.1239,
  "drawOdds": 12.7793,
  "awayOdds": 23.3032,
  "result": "home",
  "score": "3-0",
  "homeRank": 6,
  "awayRank": 83,
  "rankDiff": -77,
  "favorite": "home",
  "kickoff": "2026-06-20 08:30"
 },
 {
  "n": 30,
  "title": "Scotland vs. Morocco",
  "home": "Scotland",
  "away": "Morocco",
  "homeZh": "苏格兰",
  "awayZh": "摩洛哥",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "C",
  "homeOdds": 6.25,
  "drawOdds": 3.7046,
  "awayOdds": 1.6668,
  "result": "away",
  "score": "0-1",
  "homeRank": 42,
  "awayRank": 7,
  "rankDiff": 35,
  "favorite": "away",
  "kickoff": "2026-06-20 06:00"
 },
 {
  "n": 31,
  "title": "Türkiye vs. Paraguay",
  "home": "Türkiye",
  "away": "Paraguay",
  "homeZh": "土耳其",
  "awayZh": "巴拉圭",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "D",
  "homeOdds": 2.0795,
  "drawOdds": 3.4483,
  "awayOdds": 4.1697,
  "result": "away",
  "score": "0-1",
  "homeRank": 22,
  "awayRank": 41,
  "rankDiff": -19,
  "favorite": "home",
  "kickoff": "2026-06-20 11:00"
 },
 {
  "n": 32,
  "title": "United States vs. Australia",
  "home": "United States",
  "away": "Australia",
  "homeZh": "美国",
  "awayZh": "澳大利亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "D",
  "homeOdds": 1.6726,
  "drawOdds": 4.3777,
  "awayOdds": 5.2643,
  "result": "home",
  "score": "2-0",
  "homeRank": 17,
  "awayRank": 27,
  "rankDiff": -10,
  "favorite": "home",
  "kickoff": "2026-06-20 03:00"
 },
 {
  "n": 33,
  "title": "Germany vs. Côte d'Ivoire",
  "home": "Germany",
  "away": "Côte d'Ivoire",
  "homeZh": "德国",
  "awayZh": "科特迪瓦",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "E",
  "homeOdds": 1.4497,
  "drawOdds": 5.2478,
  "awayOdds": 8.222,
  "result": "home",
  "score": "2-1",
  "homeRank": 10,
  "awayRank": 33,
  "rankDiff": -23,
  "favorite": "home",
  "kickoff": "2026-06-21 04:00"
 },
 {
  "n": 34,
  "title": "Ecuador vs. Curaçao",
  "home": "Ecuador",
  "away": "Curaçao",
  "homeZh": "厄瓜多尔",
  "awayZh": "库拉索",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "E",
  "homeOdds": 1.1765,
  "drawOdds": 9.0909,
  "awayOdds": 17.8673,
  "result": "draw",
  "score": "0-0",
  "homeRank": 23,
  "awayRank": 82,
  "rankDiff": -59,
  "favorite": "home",
  "kickoff": "2026-06-21 08:00"
 },
 {
  "n": 35,
  "title": "Netherlands vs. Sweden",
  "home": "Netherlands",
  "away": "Sweden",
  "homeZh": "荷兰",
  "awayZh": "瑞典",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "F",
  "homeOdds": 1.7246,
  "drawOdds": 4.1667,
  "awayOdds": 4.7622,
  "result": "home",
  "score": "5-1",
  "homeRank": 8,
  "awayRank": 38,
  "rankDiff": -30,
  "favorite": "home",
  "kickoff": "2026-06-21 01:00"
 },
 {
  "n": 36,
  "title": "Tunisia vs. Japan",
  "home": "Tunisia",
  "away": "Japan",
  "homeZh": "突尼斯",
  "awayZh": "日本",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "F",
  "homeOdds": 9.0958,
  "drawOdds": 4.7626,
  "awayOdds": 1.4426,
  "result": "away",
  "score": "0-4",
  "homeRank": 45,
  "awayRank": 18,
  "rankDiff": 27,
  "favorite": "away",
  "kickoff": "2026-06-21 12:00"
 },
 {
  "n": 37,
  "title": "Uruguay vs. Cabo Verde",
  "home": "Uruguay",
  "away": "Cabo Verde",
  "homeZh": "乌拉圭",
  "awayZh": "佛得角",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "H",
  "homeOdds": 1.4287,
  "drawOdds": 4.5455,
  "awayOdds": 10.0,
  "result": "draw",
  "score": "2-2",
  "homeRank": 16,
  "awayRank": 67,
  "rankDiff": -51,
  "favorite": "home",
  "kickoff": "2026-06-22 06:00"
 },
 {
  "n": 38,
  "title": "Spain vs. Saudi Arabia",
  "home": "Spain",
  "away": "Saudi Arabia",
  "homeZh": "西班牙",
  "awayZh": "沙特阿拉伯",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "H",
  "homeOdds": 1.1111,
  "drawOdds": 12.5,
  "awayOdds": 27.027,
  "result": "home",
  "score": "4-0",
  "homeRank": 2,
  "awayRank": 61,
  "rankDiff": -59,
  "favorite": "home",
  "kickoff": "2026-06-22 00:00"
 },
 {
  "n": 39,
  "title": "Belgium vs. IR Iran",
  "home": "Belgium",
  "away": "IR Iran",
  "homeZh": "比利时",
  "awayZh": "伊朗",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "G",
  "homeOdds": 1.429,
  "drawOdds": 5.003,
  "awayOdds": 9.0909,
  "result": "draw",
  "score": "0-0",
  "homeRank": 9,
  "awayRank": 20,
  "rankDiff": -11,
  "favorite": "home",
  "kickoff": "2026-06-22 03:00"
 },
 {
  "n": 40,
  "title": "New Zealand vs. Egypt",
  "home": "New Zealand",
  "away": "Egypt",
  "homeZh": "新西兰",
  "awayZh": "埃及",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "G",
  "homeOdds": 6.2607,
  "drawOdds": 4.1667,
  "awayOdds": 1.6129,
  "result": "away",
  "score": "1-3",
  "homeRank": 85,
  "awayRank": 29,
  "rankDiff": 56,
  "favorite": "away",
  "kickoff": "2026-06-22 09:00"
 },
 {
  "n": 41,
  "title": "Norway vs. Senegal",
  "home": "Norway",
  "away": "Senegal",
  "homeZh": "挪威",
  "awayZh": "塞内加尔",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "I",
  "homeOdds": 2.3811,
  "drawOdds": 3.4483,
  "awayOdds": 3.1287,
  "result": "home",
  "score": "3-2",
  "homeRank": 31,
  "awayRank": 15,
  "rankDiff": 16,
  "favorite": "home",
  "kickoff": "2026-06-23 08:00"
 },
 {
  "n": 42,
  "title": "France vs. Iraq",
  "home": "France",
  "away": "Iraq",
  "homeZh": "法国",
  "awayZh": "伊拉克",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "I",
  "homeOdds": 1.087,
  "drawOdds": 14.2857,
  "awayOdds": 44.0601,
  "result": "home",
  "score": "3-0",
  "homeRank": 3,
  "awayRank": 57,
  "rankDiff": -54,
  "favorite": "home",
  "kickoff": "2026-06-23 05:00"
 },
 {
  "n": 43,
  "title": "Argentina vs. Austria",
  "home": "Argentina",
  "away": "Austria",
  "homeZh": "阿根廷",
  "awayZh": "奥地利",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "J",
  "homeOdds": 1.4707,
  "drawOdds": 4.5815,
  "awayOdds": 8.3333,
  "result": "home",
  "score": "2-0",
  "homeRank": 1,
  "awayRank": 24,
  "rankDiff": -23,
  "favorite": "home",
  "kickoff": "2026-06-23 01:00"
 },
 {
  "n": 44,
  "title": "Jordan vs. Algeria",
  "home": "Jordan",
  "away": "Algeria",
  "homeZh": "约旦",
  "awayZh": "阿尔及利亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "J",
  "homeOdds": 7.1429,
  "drawOdds": 4.4618,
  "awayOdds": 1.5385,
  "result": "away",
  "score": "1-2",
  "homeRank": 63,
  "awayRank": 28,
  "rankDiff": 35,
  "favorite": "away",
  "kickoff": "2026-06-23 11:00"
 },
 {
  "n": 45,
  "title": "England vs. Ghana",
  "home": "England",
  "away": "Ghana",
  "homeZh": "英格兰",
  "awayZh": "加纳",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "L",
  "homeOdds": 1.1907,
  "drawOdds": 7.6923,
  "awayOdds": 16.6667,
  "result": "draw",
  "score": "0-0",
  "homeRank": 4,
  "awayRank": 73,
  "rankDiff": -69,
  "favorite": "home",
  "kickoff": "2026-06-24 04:00"
 },
 {
  "n": 46,
  "title": "Panama vs. Croatia",
  "home": "Panama",
  "away": "Croatia",
  "homeZh": "巴拿马",
  "awayZh": "克罗地亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "L",
  "homeOdds": 8.3333,
  "drawOdds": 4.7637,
  "awayOdds": 1.4711,
  "result": "away",
  "score": "0-1",
  "homeRank": 34,
  "awayRank": 11,
  "rankDiff": 23,
  "favorite": "away",
  "kickoff": "2026-06-24 07:00"
 },
 {
  "n": 47,
  "title": "Portugal vs. Uzbekistan",
  "home": "Portugal",
  "away": "Uzbekistan",
  "homeZh": "葡萄牙",
  "awayZh": "乌兹别克斯坦",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "K",
  "homeOdds": 1.1629,
  "drawOdds": 9.0919,
  "awayOdds": 20.0,
  "result": "home",
  "score": "5-0",
  "homeRank": 5,
  "awayRank": 50,
  "rankDiff": -45,
  "favorite": "home",
  "kickoff": "2026-06-24 01:00"
 },
 {
  "n": 48,
  "title": "Colombia vs. DR Congo",
  "home": "Colombia",
  "away": "DR Congo",
  "homeZh": "哥伦比亚",
  "awayZh": "刚果民主共和国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 2,
  "group": "K",
  "homeOdds": 1.5631,
  "drawOdds": 4.1682,
  "awayOdds": 7.2129,
  "result": "home",
  "score": "1-0",
  "homeRank": 13,
  "awayRank": 46,
  "rankDiff": -33,
  "favorite": "home",
  "kickoff": "2026-06-24 10:00"
 },
 {
  "n": 50,
  "title": "Morocco vs. Haiti",
  "home": "Morocco",
  "away": "Haiti",
  "homeZh": "摩洛哥",
  "awayZh": "海地",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "C",
  "homeOdds": 1.2195,
  "drawOdds": 7.1429,
  "awayOdds": 16.6665,
  "result": "home",
  "score": "4-2",
  "homeRank": 7,
  "awayRank": 83,
  "rankDiff": -76,
  "favorite": "home",
  "kickoff": "2026-06-25 06:00"
 },
 {
  "n": 50,
  "title": "Scotland vs. Brazil",
  "home": "Scotland",
  "away": "Brazil",
  "homeZh": "苏格兰",
  "awayZh": "巴西",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "C",
  "homeOdds": 11.1152,
  "drawOdds": 5.8824,
  "awayOdds": 1.3333,
  "result": "away",
  "score": "0-3",
  "homeRank": 42,
  "awayRank": 6,
  "rankDiff": 36,
  "favorite": "away",
  "kickoff": "2026-06-25 06:00"
 },
 {
  "n": 52,
  "title": "Switzerland vs. Canada",
  "home": "Switzerland",
  "away": "Canada",
  "homeZh": "瑞士",
  "awayZh": "加拿大",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "B",
  "homeOdds": 2.5662,
  "drawOdds": 3.0813,
  "awayOdds": 3.3333,
  "result": "home",
  "score": "2-1",
  "homeRank": 19,
  "awayRank": 30,
  "rankDiff": -11,
  "favorite": "home",
  "kickoff": "2026-06-25 03:00"
 },
 {
  "n": 52,
  "title": "Bosnia-Herzegovina vs. Qatar",
  "home": "Bosnia-Herzegovina",
  "away": "Qatar",
  "homeZh": "波黑",
  "awayZh": "卡塔尔",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "B",
  "homeOdds": 1.389,
  "drawOdds": 5.8824,
  "awayOdds": 8.3333,
  "result": "home",
  "score": "3-1",
  "homeRank": 64,
  "awayRank": 56,
  "rankDiff": 8,
  "favorite": "home",
  "kickoff": "2026-06-25 03:00"
 },
 {
  "n": 54,
  "title": "Czechia vs. Mexico",
  "home": "Czechia",
  "away": "Mexico",
  "homeZh": "捷克",
  "awayZh": "墨西哥",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "A",
  "homeOdds": 4.5522,
  "drawOdds": 4.1667,
  "awayOdds": 1.8184,
  "result": "away",
  "score": "0-3",
  "homeRank": 40,
  "awayRank": 14,
  "rankDiff": 26,
  "favorite": "away",
  "kickoff": "2026-06-25 09:00"
 },
 {
  "n": 54,
  "title": "South Africa vs. Korea Republic",
  "home": "South Africa",
  "away": "Korea Republic",
  "homeZh": "南非",
  "awayZh": "韩国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "A",
  "homeOdds": 5.8921,
  "drawOdds": 3.8462,
  "awayOdds": 1.7242,
  "result": "home",
  "score": "1-0",
  "homeRank": 60,
  "awayRank": 25,
  "rankDiff": 35,
  "favorite": "away",
  "kickoff": "2026-06-25 09:00"
 },
 {
  "n": 56,
  "title": "Ecuador vs. Germany",
  "home": "Ecuador",
  "away": "Germany",
  "homeZh": "厄瓜多尔",
  "awayZh": "德国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "E",
  "homeOdds": 5.2242,
  "drawOdds": 4.9228,
  "awayOdds": 1.6405,
  "result": "home",
  "score": "2-1",
  "homeRank": 23,
  "awayRank": 10,
  "rankDiff": 13,
  "favorite": "away",
  "kickoff": "2026-06-26 04:00"
 },
 {
  "n": 56,
  "title": "Curaçao vs. Côte d'Ivoire",
  "home": "Curaçao",
  "away": "Côte d'Ivoire",
  "homeZh": "库拉索",
  "awayZh": "科特迪瓦",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "E",
  "homeOdds": 16.6824,
  "drawOdds": 8.4425,
  "awayOdds": 1.2092,
  "result": "away",
  "score": "0-2",
  "homeRank": 82,
  "awayRank": 33,
  "rankDiff": 49,
  "favorite": "away",
  "kickoff": "2026-06-26 04:00"
 },
 {
  "n": 58,
  "title": "Japan vs. Sweden",
  "home": "Japan",
  "away": "Sweden",
  "homeZh": "日本",
  "awayZh": "瑞典",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "F",
  "homeOdds": 2.2612,
  "drawOdds": 3.5587,
  "awayOdds": 3.5864,
  "result": "draw",
  "score": "1-1",
  "homeRank": 18,
  "awayRank": 38,
  "rankDiff": -20,
  "favorite": "home",
  "kickoff": "2026-06-26 07:00"
 },
 {
  "n": 58,
  "title": "Tunisia vs. Netherlands",
  "home": "Tunisia",
  "away": "Netherlands",
  "homeZh": "突尼斯",
  "awayZh": "荷兰",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "F",
  "homeOdds": 31.4668,
  "drawOdds": 11.1111,
  "awayOdds": 1.1329,
  "result": "away",
  "score": "1-3",
  "homeRank": 45,
  "awayRank": 8,
  "rankDiff": 37,
  "favorite": "away",
  "kickoff": "2026-06-26 07:00"
 },
 {
  "n": 60,
  "title": "Paraguay vs. Australia",
  "home": "Paraguay",
  "away": "Australia",
  "homeZh": "巴拉圭",
  "awayZh": "澳大利亚",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "D",
  "homeOdds": 2.7027,
  "drawOdds": 2.3921,
  "awayOdds": 4.1667,
  "result": "draw",
  "score": "0-0",
  "homeRank": 41,
  "awayRank": 27,
  "rankDiff": 14,
  "favorite": "draw",
  "kickoff": "2026-06-26 10:00"
 },
 {
  "n": 60,
  "title": "Türkiye vs. United States",
  "home": "Türkiye",
  "away": "United States",
  "homeZh": "土耳其",
  "awayZh": "美国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "D",
  "homeOdds": 3.7881,
  "drawOdds": 4.348,
  "awayOdds": 1.9613,
  "result": "home",
  "score": "3-2",
  "homeRank": 22,
  "awayRank": 17,
  "rankDiff": 5,
  "favorite": "away",
  "kickoff": "2026-06-26 10:00"
 },
 {
  "n": 62,
  "title": "Norway vs. France",
  "home": "Norway",
  "away": "France",
  "homeZh": "挪威",
  "awayZh": "法国",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "I",
  "homeOdds": 7.6952,
  "drawOdds": 5.5572,
  "awayOdds": 1.4297,
  "result": "away",
  "score": "1-4",
  "homeRank": 31,
  "awayRank": 3,
  "rankDiff": 28,
  "favorite": "away",
  "kickoff": "2026-06-27 03:00"
 },
 {
  "n": 62,
  "title": "Senegal vs. Iraq",
  "home": "Senegal",
  "away": "Iraq",
  "homeZh": "塞内加尔",
  "awayZh": "伊拉克",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "I",
  "homeOdds": 1.2657,
  "drawOdds": 7.1429,
  "awayOdds": 12.5309,
  "result": "home",
  "score": "5-0",
  "homeRank": 15,
  "awayRank": 57,
  "rankDiff": -42,
  "favorite": "home",
  "kickoff": "2026-06-27 03:00"
 },
 {
  "n": 64,
  "title": "Egypt vs. IR Iran",
  "home": "Egypt",
  "away": "IR Iran",
  "homeZh": "埃及",
  "awayZh": "伊朗",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "G",
  "homeOdds": 2.7027,
  "drawOdds": 2.7778,
  "awayOdds": 3.4483,
  "result": "draw",
  "score": "1-1",
  "homeRank": 29,
  "awayRank": 20,
  "rankDiff": 9,
  "favorite": "home",
  "kickoff": "2026-06-27 11:00"
 },
 {
  "n": 64,
  "title": "New Zealand vs. Belgium",
  "home": "New Zealand",
  "away": "Belgium",
  "homeZh": "新西兰",
  "awayZh": "比利时",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "G",
  "homeOdds": 13.8965,
  "drawOdds": 8.4208,
  "awayOdds": 1.2229,
  "result": "away",
  "score": "1-5",
  "homeRank": 85,
  "awayRank": 9,
  "rankDiff": 76,
  "favorite": "away",
  "kickoff": "2026-06-27 11:00"
 },
 {
  "n": 66,
  "title": "Cabo Verde vs. Saudi Arabia",
  "home": "Cabo Verde",
  "away": "Saudi Arabia",
  "homeZh": "佛得角",
  "awayZh": "沙特阿拉伯",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "H",
  "homeOdds": 3.0339,
  "drawOdds": 3.449,
  "awayOdds": 2.6057,
  "result": "draw",
  "score": "0-0",
  "homeRank": 67,
  "awayRank": 61,
  "rankDiff": 6,
  "favorite": "away",
  "kickoff": "2026-06-27 08:00"
 },
 {
  "n": 66,
  "title": "Uruguay vs. Spain",
  "home": "Uruguay",
  "away": "Spain",
  "homeZh": "乌拉圭",
  "awayZh": "西班牙",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "H",
  "homeOdds": 6.666,
  "drawOdds": 3.8461,
  "awayOdds": 1.6694,
  "result": "away",
  "score": "0-1",
  "homeRank": 16,
  "awayRank": 2,
  "rankDiff": 14,
  "favorite": "away",
  "kickoff": "2026-06-27 08:00"
 },
 {
  "n": 68,
  "title": "Panama vs. England",
  "home": "Panama",
  "away": "England",
  "homeZh": "巴拿马",
  "awayZh": "英格兰",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "L",
  "homeOdds": 20.0,
  "drawOdds": 9.0989,
  "awayOdds": 1.1628,
  "result": "away",
  "score": "0-2",
  "homeRank": 34,
  "awayRank": 4,
  "rankDiff": 30,
  "favorite": "away",
  "kickoff": "2026-06-28 05:00"
 },
 {
  "n": 68,
  "title": "Croatia vs. Ghana",
  "home": "Croatia",
  "away": "Ghana",
  "homeZh": "克罗地亚",
  "awayZh": "加纳",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "L",
  "homeOdds": 1.8196,
  "drawOdds": 3.3305,
  "awayOdds": 5.8837,
  "result": "home",
  "score": "2-1",
  "homeRank": 11,
  "awayRank": 73,
  "rankDiff": -62,
  "favorite": "home",
  "kickoff": "2026-06-28 05:00"
 },
 {
  "n": 70,
  "title": "Jordan vs. Argentina",
  "home": "Jordan",
  "away": "Argentina",
  "homeZh": "约旦",
  "awayZh": "阿根廷",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "J",
  "homeOdds": 22.9761,
  "drawOdds": 10.0,
  "awayOdds": 1.1505,
  "result": "away",
  "score": "1-3",
  "homeRank": 63,
  "awayRank": 1,
  "rankDiff": 62,
  "favorite": "away",
  "kickoff": "2026-06-28 10:00"
 },
 {
  "n": 70,
  "title": "Algeria vs. Austria",
  "home": "Algeria",
  "away": "Austria",
  "homeZh": "阿尔及利亚",
  "awayZh": "奥地利",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "J",
  "homeOdds": 3.5714,
  "drawOdds": 2.1303,
  "awayOdds": 3.7037,
  "result": "draw",
  "score": "3-3",
  "homeRank": 28,
  "awayRank": 24,
  "rankDiff": 4,
  "favorite": "draw",
  "kickoff": "2026-06-28 10:00"
 },
 {
  "n": 72,
  "title": "Colombia vs. Portugal",
  "home": "Colombia",
  "away": "Portugal",
  "homeZh": "哥伦比亚",
  "awayZh": "葡萄牙",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "K",
  "homeOdds": 3.847,
  "drawOdds": 4.1672,
  "awayOdds": 1.9263,
  "result": "draw",
  "score": "0-0",
  "homeRank": 13,
  "awayRank": 5,
  "rankDiff": 8,
  "favorite": "away",
  "kickoff": "2026-06-28 07:30"
 },
 {
  "n": 72,
  "title": "DR Congo vs. Uzbekistan",
  "home": "DR Congo",
  "away": "Uzbekistan",
  "homeZh": "刚果民主共和国",
  "awayZh": "乌兹别克斯坦",
  "stage": "group-stage",
  "stageOrder": 1,
  "matchday": 3,
  "group": "K",
  "homeOdds": 1.6954,
  "drawOdds": 4.0,
  "awayOdds": 5.5556,
  "result": "home",
  "score": "3-1",
  "homeRank": 46,
  "awayRank": 50,
  "rankDiff": -4,
  "favorite": "home",
  "kickoff": "2026-06-28 07:30"
 },
 {
  "n": 73,
  "title": "South Africa vs. Canada",
  "home": "South Africa",
  "away": "Canada",
  "homeZh": "南非",
  "awayZh": "加拿大",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 5.557,
  "drawOdds": 3.4485,
  "awayOdds": 1.8871,
  "result": "away",
  "score": "0-1",
  "homeRank": 60,
  "awayRank": 30,
  "rankDiff": 30,
  "favorite": "away",
  "kickoff": "2026-06-29 03:00"
 },
 {
  "n": 74,
  "title": "Germany vs. Paraguay",
  "home": "Germany",
  "away": "Paraguay",
  "homeZh": "德国",
  "awayZh": "巴拉圭",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.3514,
  "drawOdds": 5.265,
  "awayOdds": 12.0246,
  "result": "draw",
  "score": "1-1",
  "homeRank": 10,
  "awayRank": 41,
  "rankDiff": -31,
  "favorite": "home",
  "kickoff": "2026-06-30 04:30"
 },
 {
  "n": 75,
  "title": "Netherlands vs. Morocco",
  "home": "Netherlands",
  "away": "Morocco",
  "homeZh": "荷兰",
  "awayZh": "摩洛哥",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.4392,
  "drawOdds": 3.1286,
  "awayOdds": 3.4619,
  "result": "draw",
  "score": "1-1",
  "homeRank": 8,
  "awayRank": 7,
  "rankDiff": 1,
  "favorite": "home",
  "kickoff": "2026-06-30 09:00"
 },
 {
  "n": 76,
  "title": "Brazil vs. Japan",
  "home": "Brazil",
  "away": "Japan",
  "homeZh": "巴西",
  "awayZh": "日本",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.7858,
  "drawOdds": 3.7039,
  "awayOdds": 5.3068,
  "result": "home",
  "score": "2-1",
  "homeRank": 6,
  "awayRank": 18,
  "rankDiff": -12,
  "favorite": "home",
  "kickoff": "2026-06-30 01:00"
 },
 {
  "n": 77,
  "title": "France vs. Sweden",
  "home": "France",
  "away": "Sweden",
  "homeZh": "法国",
  "awayZh": "瑞典",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.2821,
  "drawOdds": 6.2638,
  "awayOdds": 12.9882,
  "result": "home",
  "score": "3-0",
  "homeRank": 3,
  "awayRank": 38,
  "rankDiff": -35,
  "favorite": "home",
  "kickoff": "2026-07-01 05:00"
 },
 {
  "n": 78,
  "title": "Côte d'Ivoire vs. Norway",
  "home": "Côte d'Ivoire",
  "away": "Norway",
  "homeZh": "科特迪瓦",
  "awayZh": "挪威",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 3.8451,
  "drawOdds": 3.4483,
  "awayOdds": 2.2276,
  "result": "away",
  "score": "1-2",
  "homeRank": 33,
  "awayRank": 31,
  "rankDiff": 2,
  "favorite": "away",
  "kickoff": "2026-07-01 01:00"
 },
 {
  "n": 79,
  "title": "Mexico vs. Ecuador",
  "home": "Mexico",
  "away": "Ecuador",
  "homeZh": "墨西哥",
  "awayZh": "厄瓜多尔",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.2728,
  "drawOdds": 2.9412,
  "awayOdds": 4.3464,
  "result": "home",
  "score": "2-0",
  "homeRank": 14,
  "awayRank": 23,
  "rankDiff": -9,
  "favorite": "home",
  "kickoff": "2026-07-01 09:00"
 },
 {
  "n": 80,
  "title": "England vs. DR Congo",
  "home": "England",
  "away": "DR Congo",
  "homeZh": "英格兰",
  "awayZh": "刚果民主共和国",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.3034,
  "drawOdds": 5.3207,
  "awayOdds": 16.6667,
  "result": "home",
  "score": "2-1",
  "homeRank": 4,
  "awayRank": 46,
  "rankDiff": -42,
  "favorite": "home",
  "kickoff": "2026-07-02 00:00"
 },
 {
  "n": 81,
  "title": "United States vs. Bosnia and Herzegovina",
  "home": "United States",
  "away": "Bosnia and Herzegovina",
  "homeZh": "美国",
  "awayZh": "波黑",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.3908,
  "drawOdds": 5.2632,
  "awayOdds": 10.0,
  "result": "home",
  "score": "2-0",
  "homeRank": 17,
  "awayRank": 64,
  "rankDiff": -47,
  "favorite": "home",
  "kickoff": "2026-07-02 08:00"
 },
 {
  "n": 82,
  "title": "Belgium vs. Senegal",
  "home": "Belgium",
  "away": "Senegal",
  "homeZh": "比利时",
  "awayZh": "塞内加尔",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.1852,
  "drawOdds": 3.3333,
  "awayOdds": 3.8519,
  "result": "draw",
  "score": "3-2",
  "homeRank": 9,
  "awayRank": 15,
  "rankDiff": -6,
  "favorite": "home",
  "kickoff": "2026-07-02 04:00"
 },
 {
  "n": 83,
  "title": "Portugal vs. Croatia",
  "home": "Portugal",
  "away": "Croatia",
  "homeZh": "葡萄牙",
  "awayZh": "克罗地亚",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.7316,
  "drawOdds": 3.78,
  "awayOdds": 6.0609,
  "result": "home",
  "score": "2-1",
  "homeRank": 5,
  "awayRank": 11,
  "rankDiff": -6,
  "favorite": "home",
  "kickoff": "2026-07-03 07:00"
 },
 {
  "n": 84,
  "title": "Spain vs. Austria",
  "home": "Spain",
  "away": "Austria",
  "homeZh": "西班牙",
  "awayZh": "奥地利",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.3202,
  "drawOdds": 5.9696,
  "awayOdds": 13.8039,
  "result": "home",
  "score": "3-0",
  "homeRank": 2,
  "awayRank": 24,
  "rankDiff": -22,
  "favorite": "home",
  "kickoff": "2026-07-03 03:00"
 },
 {
  "n": 85,
  "title": "Switzerland vs. Algeria",
  "home": "Switzerland",
  "away": "Algeria",
  "homeZh": "瑞士",
  "awayZh": "阿尔及利亚",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.0413,
  "drawOdds": 3.2787,
  "awayOdds": 4.7059,
  "result": "home",
  "score": "2-0",
  "homeRank": 19,
  "awayRank": 28,
  "rankDiff": -9,
  "favorite": "home",
  "kickoff": "2026-07-03 11:00"
 },
 {
  "n": 86,
  "title": "Argentina vs. Cabo Verde",
  "home": "Argentina",
  "away": "Cabo Verde",
  "homeZh": "阿根廷",
  "awayZh": "佛得角",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.1628,
  "drawOdds": 9.0922,
  "awayOdds": 28.7089,
  "result": "draw",
  "score": "3-2",
  "homeRank": 1,
  "awayRank": 67,
  "rankDiff": -66,
  "favorite": "home",
  "kickoff": "2026-07-04 06:00"
 },
 {
  "n": 87,
  "title": "Colombia vs. Ghana",
  "home": "Colombia",
  "away": "Ghana",
  "homeZh": "哥伦比亚",
  "awayZh": "加纳",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.451,
  "drawOdds": 4.5502,
  "awayOdds": 9.0909,
  "result": "home",
  "score": "1-0",
  "homeRank": 13,
  "awayRank": 73,
  "rankDiff": -60,
  "favorite": "home",
  "kickoff": "2026-07-04 09:30"
 },
 {
  "n": 88,
  "title": "Australia vs. Egypt",
  "home": "Australia",
  "away": "Egypt",
  "homeZh": "澳大利亚",
  "awayZh": "埃及",
  "stage": "round-of-32",
  "stageOrder": 2,
  "matchday": 0,
  "group": "",
  "homeOdds": 3.7037,
  "drawOdds": 2.9412,
  "awayOdds": 2.439,
  "result": "draw",
  "score": "1-1",
  "homeRank": 27,
  "awayRank": 29,
  "rankDiff": -2,
  "favorite": "away",
  "kickoff": "2026-07-04 02:00"
 },
 {
  "n": 89,
  "title": "Paraguay vs. France",
  "home": "Paraguay",
  "away": "France",
  "homeZh": "巴拉圭",
  "awayZh": "法国",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 20.0237,
  "drawOdds": 7.1463,
  "awayOdds": 1.2056,
  "result": "away",
  "score": "0-1",
  "homeRank": 41,
  "awayRank": 3,
  "rankDiff": 38,
  "favorite": "away",
  "kickoff": "2026-07-05 05:00"
 },
 {
  "n": 90,
  "title": "Canada vs. Morocco",
  "home": "Canada",
  "away": "Morocco",
  "homeZh": "加拿大",
  "awayZh": "摩洛哥",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 5.5556,
  "drawOdds": 3.4483,
  "awayOdds": 1.8182,
  "result": "away",
  "score": "0-3",
  "homeRank": 30,
  "awayRank": 7,
  "rankDiff": 23,
  "favorite": "away",
  "kickoff": "2026-07-05 01:00"
 },
 {
  "n": 91,
  "title": "Brazil vs. Norway",
  "home": "Brazil",
  "away": "Norway",
  "homeZh": "巴西",
  "awayZh": "挪威",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.8188,
  "drawOdds": 3.7037,
  "awayOdds": 5.0002,
  "result": "away",
  "score": "1-2",
  "homeRank": 6,
  "awayRank": 31,
  "rankDiff": -25,
  "favorite": "home",
  "kickoff": "2026-07-06 04:00"
 },
 {
  "n": 92,
  "title": "Mexico vs. England",
  "home": "Mexico",
  "away": "England",
  "homeZh": "墨西哥",
  "awayZh": "英格兰",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 3.1304,
  "drawOdds": 3.1299,
  "awayOdds": 2.634,
  "result": "away",
  "score": "2-3",
  "homeRank": 14,
  "awayRank": 4,
  "rankDiff": 10,
  "favorite": "away",
  "kickoff": "2026-07-06 08:00"
 },
 {
  "n": 93,
  "title": "Portugal vs. Spain",
  "home": "Portugal",
  "away": "Spain",
  "homeZh": "葡萄牙",
  "awayZh": "西班牙",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 4.1668,
  "drawOdds": 3.5714,
  "awayOdds": 1.961,
  "result": "away",
  "score": "0-1",
  "homeRank": 5,
  "awayRank": 2,
  "rankDiff": 3,
  "favorite": "away",
  "kickoff": "2026-07-07 03:00"
 },
 {
  "n": 94,
  "title": "United States vs. Belgium",
  "home": "United States",
  "away": "Belgium",
  "homeZh": "美国",
  "awayZh": "比利时",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.7033,
  "drawOdds": 3.4483,
  "awayOdds": 2.8573,
  "result": "away",
  "score": "1-4",
  "homeRank": 17,
  "awayRank": 9,
  "rankDiff": 8,
  "favorite": "home",
  "kickoff": "2026-07-07 08:00"
 },
 {
  "n": 95,
  "title": "Argentina vs. Egypt",
  "home": "Argentina",
  "away": "Egypt",
  "homeZh": "阿根廷",
  "awayZh": "埃及",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.3579,
  "drawOdds": 5.0,
  "awayOdds": 12.506,
  "result": "home",
  "score": "3-2",
  "homeRank": 1,
  "awayRank": 29,
  "rankDiff": -28,
  "favorite": "home",
  "kickoff": "2026-07-08 00:00"
 },
 {
  "n": 96,
  "title": "Switzerland vs. Colombia",
  "home": "Switzerland",
  "away": "Colombia",
  "homeZh": "瑞士",
  "awayZh": "哥伦比亚",
  "stage": "round-of-16",
  "stageOrder": 3,
  "matchday": 0,
  "group": "",
  "homeOdds": 3.7039,
  "drawOdds": 3.0303,
  "awayOdds": 2.3811,
  "result": "draw",
  "score": "0-0",
  "homeRank": 19,
  "awayRank": 13,
  "rankDiff": 6,
  "favorite": "away",
  "kickoff": "2026-07-08 04:00"
 },
 {
  "n": 97,
  "title": "France vs. Morocco",
  "home": "France",
  "away": "Morocco",
  "homeZh": "法国",
  "awayZh": "摩洛哥",
  "stage": "quarter-finals",
  "stageOrder": 4,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.6327,
  "drawOdds": 3.9613,
  "awayOdds": 7.0357,
  "result": "home",
  "score": "2-0",
  "homeRank": 3,
  "awayRank": 7,
  "rankDiff": -4,
  "favorite": "home",
  "kickoff": "2026-07-10 04:00"
 },
 {
  "n": 98,
  "title": "Spain vs. Belgium",
  "home": "Spain",
  "away": "Belgium",
  "homeZh": "西班牙",
  "awayZh": "比利时",
  "stage": "quarter-finals",
  "stageOrder": 4,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.6546,
  "drawOdds": 4.0473,
  "awayOdds": 6.1898,
  "result": "home",
  "score": "2-1",
  "homeRank": 2,
  "awayRank": 9,
  "rankDiff": -7,
  "favorite": "home",
  "kickoff": "2026-07-11 03:00"
 },
 {
  "n": 99,
  "title": "Norway vs. England",
  "home": "Norway",
  "away": "England",
  "homeZh": "挪威",
  "awayZh": "英格兰",
  "stage": "quarter-finals",
  "stageOrder": 4,
  "matchday": 0,
  "group": "",
  "homeOdds": 4.3488,
  "drawOdds": 4.041,
  "awayOdds": 1.9048,
  "result": "draw",
  "score": "1-2",
  "homeRank": 31,
  "awayRank": 4,
  "rankDiff": 27,
  "favorite": "away",
  "kickoff": "2026-07-12 05:00"
 },
 {
  "n": 100,
  "title": "Argentina vs. Switzerland",
  "home": "Argentina",
  "away": "Switzerland",
  "homeZh": "阿根廷",
  "awayZh": "瑞士",
  "stage": "quarter-finals",
  "stageOrder": 4,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.7409,
  "drawOdds": 3.6365,
  "awayOdds": 6.3528,
  "result": "draw",
  "score": "3-1",
  "homeRank": 1,
  "awayRank": 19,
  "rankDiff": -18,
  "favorite": "home",
  "kickoff": "2026-07-12 09:00"
 },
 {
  "n": 101,
  "title": "France vs. Spain",
  "home": "France",
  "away": "Spain",
  "homeZh": "法国",
  "awayZh": "西班牙",
  "stage": "semi-finals",
  "stageOrder": 5,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.6501,
  "drawOdds": 3.1008,
  "awayOdds": 3.3333,
  "result": "away",
  "score": "0-2",
  "homeRank": 3,
  "awayRank": 2,
  "rankDiff": 1,
  "favorite": "home",
  "kickoff": "2026-07-15 03:00"
 },
 {
  "n": 102,
  "title": "England vs. Argentina",
  "home": "England",
  "away": "Argentina",
  "homeZh": "英格兰",
  "awayZh": "阿根廷",
  "stage": "semi-finals",
  "stageOrder": 5,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.7593,
  "drawOdds": 2.9851,
  "awayOdds": 3.2058,
  "result": "away",
  "score": "1-2",
  "homeRank": 4,
  "awayRank": 1,
  "rankDiff": 3,
  "favorite": "home",
  "kickoff": "2026-07-16 03:00"
 },
 {
  "n": 103,
  "title": "France vs. England",
  "home": "France",
  "away": "England",
  "homeZh": "法国",
  "awayZh": "英格兰",
  "stage": "third-place",
  "stageOrder": 6,
  "matchday": 0,
  "group": "",
  "homeOdds": 1.7872,
  "drawOdds": 4.3478,
  "awayOdds": 4.3478,
  "result": "away",
  "score": "4-6",
  "homeRank": 3,
  "awayRank": 4,
  "rankDiff": -1,
  "favorite": "home",
  "kickoff": "2026-07-19 05:00"
 },
 {
  "n": 104,
  "title": "Spain vs. Argentina",
  "home": "Spain",
  "away": "Argentina",
  "homeZh": "西班牙",
  "awayZh": "阿根廷",
  "stage": "final",
  "stageOrder": 7,
  "matchday": 0,
  "group": "",
  "homeOdds": 2.3396,
  "drawOdds": 3.125,
  "awayOdds": 3.8099,
  "result": "draw",
  "score": "1-0",
  "homeRank": 2,
  "awayRank": 1,
  "rankDiff": 1,
  "favorite": "home",
  "kickoff": "2026-07-20 03:00"
 }
];
